##### Fichiers source, /!\ un seul fichier par type /!\
debits = "/home/christophe/Project/data-fake/debits.csv"
cotisations = "/home/christophe/Project/data-fake/cotisations.csv"
comptes = "/home/christophe/Project/data-fake/comptes.csv"
delais = "/home/christophe/Project/data-fake/delais.csv"
sirene = "/home/christophe/Project/data-fake/geo_sirene.csv"
altares = "/home/christophe/Project/data-fake/altares.csv"

###### Les fichiers générés seront préfixés par outputPrefix
prefixOutput = "fake-"
