---
title: "Import data"
output: html_notebook
---

```{r setup}
library("opensignauxfaibles")
library("dplyr")
library("purrr")
library("RPostgreSQL")
database_signauxfaibles <- database_connect()
```

## Import table altares

```{bash}
in2csv data-raw/altares/RECAP_ALTARES_201803.xlsx > data-raw/altares/RECAP_ALTARES_201803.csv
```

```{r}
db_drop_table_ifexist(db = database_signauxfaibles, table = "table_altares")
import_table_altares(
  path = "data-raw/altares/RECAP_ALTARES_201803.csv"
  ) %>% 
  insert_multi(
    dest = database_signauxfaibles,
    df = .,
    slices = 10,
        "apart_last12_months" = 0,
        "apart_consommee" = 0,
        "apart_share_heuresconsommees" = 0,
        "apart_heures_consommees" = 0
      )
    ) %>%
    dplyr::mutate(
      cut_effectif = forcats::fct_relevel(
        dplyr::case_when(
          .$effectif < 20 ~ "10-20",
          .$effectif < 50 ~ "21-50",
          TRUE ~ "Plus de 50"
        )
      ),
      cut_growthrate = forcats::fct_relevel(
        dplyr::case_when(
          .$lag_effectif_missing == TRUE ~ "manquant",
          .$growthrate_effectif < .80 ~ "moins 20%",
          .$growthrate_effectif < .95 ~ "moins 20 à 5%",
          .$growthrate_effectif < 1.05 ~ "stable",
          .$growthrate_effectif < 1.20 ~ "plus 5 à 20%",
          TRUE ~ "plus 20%"
        ),
        c("stable", "moins 20%", "moins 20 à 5%", "plus 5 à 20%", "plus 20%", "manquant")
      ),
      outcome_0_12 = forcats::fct_explicit_na(
        factor(outcome_0_12, levels = c("non-default", "default")),
        na_level = "non-default"),
      outcome_6_18 = forcats::fct_explicit_na(
        factor(outcome_6_18, levels = c("non-default", "default")),
        na_level = "non-default"),
      outcome_12_24 = forcats::fct_explicit_na(
        factor(outcome_6_18, levels = c("non-default", "default")),
        na_level = "non-default"),
      cotisationdue_effectif = (mean_cotisation_due) / effectif,
      log_cotisationdue_effectif = log(cotisationdue_effectif),
      ratio_dettecumulee_cotisation = (montant_part_ouvriere + montant_part_patronale) / mean_cotisation_due,
      indicatrice_dettecumulee = (montant_part_ouvriere + montant_part_patronale > 0),
      log_ratio_dettecumulee_cotisation = dplyr::if_else(
        condition = indicatrice_dettecumulee == TRUE,
        true = log(ratio_dettecumulee_cotisation),
        false = 0
      ),
      ratio_dettecumulee_cotisation_12m = (montant_part_ouvriere_12m + montant_part_patronale_12m) / mean_cotisation_due,
      indicatrice_dettecumulee_12m = (montant_part_ouvriere_12m + montant_part_patronale_12m > 0),
      log_ratio_dettecumulee_cotisation_12m = dplyr::if_else(
        condition = indicatrice_dettecumulee_12m == TRUE,
        true = log(ratio_dettecumulee_cotisation_12m),
        false = 0
      ),
      indicatrice_croissance_dettecumulee = (
        montant_part_ouvriere + montant_part_patronale > lag_montant_part_ouvriere + lag_montant_part_patronale
      )
    )
}



    name = "table_altares"
    );
```

### Tables des codes RJ/LJ

```{r import-code-rjlj}
table_code_rj_lj <- tibble::tibble(
  code = c(
    "PCL010501",
    "PCL010502",
    "PCL030105",
    "PCL05010102",
    "PCL05010203",
    "PCL05010402",
    "PCL05010302",
    "PCL05010502",
    "PCL05010702",
    "PCL05010802",
    "PCL05010901",
    "PCL05011003",
    "PCL05011101",
    "PCL05011203",
    "PCL05011303",
    "PCL05011403",
    "PCL05011503",
    "PCL05011603",
    "PCL05011902",
    "PCL05012003",
    "PCL0108",
    "PCL0109",
    "PCL030107",
    "PCL030108",
    "PCL030307",
    "PCL030308",
    "PCL05010103",
    "PCL05010104",
    "PCL05010204",
    "PCL05010205",
    "PCL05010303",
    "PCL05010304",
    "PCL05010403",
    "PCL05010404",
    "PCL05010503",
    "PCL05010504",
    "PCL05010703",
    "PCL05010803",
    "PCL05011004",
    "PCL05011005",
    "PCL05011102",
    "PCL05011103",
    "PCL05011204",
    "PCL05011205",
    "PCL05011304",
    "PCL05011305",
    "PCL05011404",
    "PCL05011405",
    "PCL05011504",
    "PCL05011505",
    "PCL05011604",
    "PCL05011605",
    "PCL05011903",
    "PCL05011904",
    "PCL05012004",
    "PCL05012005",
    "PCL040802",
    "PCL0106",
    "PCL010601",
    "PCL030103",
    "PCL05010101",
    "PCL05010202",
    "PCL05010301",
    "PCL05010401",
    "PCL05010501",
    "PCL05010506",
    "PCL05010101",
    "PCL05010202",
    "PCL05010301",
    "PCL05010401",
    "PCL05010501",
    "PCL05010506",
    "PCL05010701",
    "PCL05010705",
    "PCL05010801",
    "PCL05010805",
    "PCL05011002",
    "PCL05011202",
    "PCL05011302",
    "PCL05011402",
    "PCL05011502",
    "PCL05011602",
    "PCL05011901",
    "PCL0114",
    "PCL030110"
))

db_drop_table_ifexist(db = database_signauxfaibles, table = "table_code_rj_lj")
copy_to(dest = database_signauxfaibles, df = table_code_rj_lj, temporary = FALSE)
```

## Activité partielle - demandes

```{r import_apart}
db_drop_table_ifexist(db = database_signauxfaibles, table = "table_activitepartielle")

dplyr::bind_rows(
  import_table_activite_partielle(
    path = "data-raw/activite_partielle/act_partielle_ddes_2012_fév2018.xlsx",
    hta = "hta",
    mta = "mta",
    effectif_autorise = "eff_auto"
    )
  ) %>%
  dplyr::distinct() %>%
  insert_multi(
    dest = database_signauxfaibles,
    df = .,
    slices=10,
    name = "table_activitepartielle"
    )
```

### Heures consommées

```{r import-apart-heuresconsommees}
db_drop_table_ifexist(db = database_signauxfaibles, table = "table_apart_consommee")

  import_apart_heuresconsommees(
    path = "data-raw/activite_partielle/act_partielle_conso_fév2018.xlsx",
    sheet = "INDEMNITE",
    skip = 0,
    date = "mois",
    effectif_concerne = "effectifs",
    heures_consommees = "heures",
    montants = "montants"
    ) %>% 
  dplyr::filter(id_da != "") %>%
  dplyr::rename(id_da_long = id_da) %>%
  dplyr::mutate("id_da" = substring(id_da_long, 0, 10)) %>%
  dplyr::distinct() %>%
  insert_multi(
    dest = database_signauxfaibles,
    df = .,
    slices=10,
    name = "table_apart_consommee"
    )
```

## Banque de France

```{r banque_de_france}
db_drop_table_ifexist(db = database_signauxfaibles, table = "table_banquedefrance")

table_temp <-
readxl::read_excel(path = "data-raw/banque_de_france/201712.xlsx")
table_temp %>% rename(
"siren" = "d1",
"annee" = "Annee",
"bilan" = "ARRETE_BILAN",
"raison_sociale" = "DENOM",
"secteur" = "SECTEUR",
"poids_frng" = "POIDS_FRNG",
"taux_marge" = "TX_MARGE",
"delai_fournisseur" = "DELAI_FRS",
"dette_fiscale" = "POIDS_DFISC_SOC",
"financier_ct" = "POIDS_FIN_CT",
"financier" = "POIDS_FRAIS_FIN"
) %>%
mutate(siren = stringr::str_replace_all(.$siren, " ", ""))  %>%
insert_multi(
dest = database_signauxfaibles,
df = .,
slices = 3,
name = "table_banquedefrance"
)
```

## Cotisations URSSAF

```{r import-cotisations}
db_drop_table_ifexist(
  db = database_signauxfaibles,
  table = "table_cotisation"
  )

dplyr::bind_rows(
    import_table_cotisation(    path = "data-raw/cotisations/cotisations_bourgogne_0_201608.txt"),
    import_table_cotisation_csv(path = "data-raw/cotisations/cotisations_bourgogne_201609_201701.csv"),
    import_table_cotisation_csv(path = "data-raw/cotisations/cotisations_bourgogne_201702_201703.csv"),
    import_table_cotisation_csv(path = "data-raw/cotisations/cotisations_bourgogne_201704_201707.csv"),
    import_table_cotisation_csv(path = "data-raw/cotisations/cotisations_bourgogne_201708_201710.csv"),
    import_table_cotisation_csv(path = "data-raw/cotisations/cotisations_bourgogne_201711.csv"),
    import_table_cotisation_csv(path = "data-raw/cotisations/cotisations_bourgogne_201712.csv"),
    import_table_cotisation_csv(path = "data-raw/cotisations/cotisations_bourgogne_201801.csv"),
    import_table_cotisation_csv(path = "data-raw/cotisations/cotisations_bourgogne_201802.csv"),
    import_table_cotisation(    path = "data-raw/cotisations/cotisations_frc_0_201701.txt"),
    import_table_cotisation_csv(path = "data-raw/cotisations/cotisations_frc_201702_201703.csv"),
    import_table_cotisation_csv(path = "data-raw/cotisations/cotisations_frc_201704_201707.csv"),
    import_table_cotisation_csv(path = "data-raw/cotisations/cotisations_frc_201708_201710.csv"),
    import_table_cotisation_csv(path = "data-raw/cotisations/cotisations_frc_201711.csv"),
    import_table_cotisation_csv(path = "data-raw/cotisations/cotisations_frc_201712.csv"),
    import_table_cotisation_csv(path = "data-raw/cotisations/cotisations_frc_201801.csv"),
    import_table_cotisation_csv(path = "data-raw/cotisations/cotisations_frc_201802.csv")
  ) %>%
  dplyr::distinct() %>%
  insert_multi(
    dest = database_signauxfaibles,
    df = .,
    name = "table_cotisation",
    slices = 100,
    indexes = list("numero_compte", "period")
    )
```

## Débits URSSAF

```{r import-debits}
db_drop_table_ifexist(
  db = database_signauxfaibles,
  table = "table_debit"
)

purrr::map(
  .x = dir(path = "data-raw/debits/", pattern = "*\\.csv") %>%
    paste0("data-raw/debits/", .),
  .f = import_table_debit
  ) %>%
  dplyr::bind_rows() %>%
  dplyr::distinct() %>%
  insert_multi(
    dest = database_signauxfaibles,
    df = .,
    name = "table_debit",
    slices = 100
  )
```

## Effectifs

```{r import-effectif}
db_drop_table_ifexist(
  db = database_signauxfaibles,
  table = "table_effectif"
  )

import_table_effectif2(
  path = "data-raw/effectif/Urssaf_emploi_BFC_201001_201801.csv"
  ) %>%
  insert_multi(
    dest = database_signauxfaibles,
    df = .,
    name = "table_effectif",
    slice = 200
    )
```

<!-- ## NAF -->

<!-- ```{r} -->
<!-- import_table_naf(path = "data-raw/naf/naf2008_5_niveaux.xls") %>% -->
<!--   glimpse() -->
<!-- ``` -->

## Données CCSF

```{r import-ccsv}
db_drop_table_ifexist(db = database_signauxfaibles, "table_ccsv")

dplyr::bind_rows(
  import_table_ccsv(path = "data-raw/ccsv/Bourgogne_ccsf_201803.csv"),
  import_table_ccsv(path = "data-raw/ccsv/FRC_ccsf_201803.csv")
  ) %>%
  dplyr::distinct() %>%
  insert_multi(
    dest = database_signauxfaibles,
    df = .,
    name = "table_ccsv",
    slices = 1,
    indexes = list("numero_compte")
  )
```

## Délais URSSAF

```{r import-delais}
db_drop_table_ifexist(db = database_signauxfaibles, "table_delais")

purrr::map(
  .x = dir(path = "data-raw/delais/", pattern = "*.csv") %>%
    paste0("data-raw/delais/", .),
  .f = import_table_delais
  ) %>%
  dplyr::bind_rows() %>%
  dplyr::distinct() %>%
  insert_multi(
    dest = database_signauxfaibles,
    df = .,
    name = "table_delais",
    slices = 10
    )
```

<!-- ## SIRENE -->

<!-- -> On n'importe plus SIRENE -->

<!-- ```{r} -->
<!-- import_table_sirene(path = "data-raw/direccte/sirene/bfc.sas7bdat") %>% insert_multi( -->
<!--     dest = database_signauxfaibles, -->
<!--     df = ., -->
<!--     name = "table_sirene", -->
<!--     slices = 10 -->
<!--     ) -->
<!-- ``` -->

