---
title: "Model_evaluation"
author: "Pierre Camilleri"
date: "3 avril 2018"
output: html_document
---

```{r}

#F-score

models = list(log1 = logmodel, log2 = logmodel)

# If one model
(models[[1]]$resample)

# If several models
results <- resamples(models)
summary(results)
bwplot(results)
dotplot(results)

  
# obs: observed training and test data
# pred: predicted values
# model: the type of model  used to predict
# object: names of the objects within models.
# dataType: "training", "test" or "unknown"
```

```{r}
# confusion matrix
model_investigated = "log1"; 

training_preds <- predict(models[[model_investigated]],newdata = sample_train, type = "raw")

test_preds <- predict(models[[model_investigated]],newdata = sample_test)
(resultTest <- confusionMatrix(ifelse(test_preds > threshold,'default','non_default'),sample_test$outcome))
resultTest$byClass['F1']


```

```{r}
# Same with probabilities and F-score optimization

model_investigated = "log1"; 

#training_preds <- predict(models[[model_investigated]],newdata = sample_train, type = "prob")

thresholder(models[[model_investigated]], threshold = seq(0.05,0.8,0.01), final = TRUE)

threshold <- 0.5

test_preds <- predict(models[[model_investigated]],newdata = sample_test,type = "prob")
test_preds <- test_preds[['default']]
(resultTest <- confusionMatrix(ifelse(test_preds > threshold,'default','non_default'),sample_test$outcome))
resultTest$byClass['F1']
```

```{r}
positive_preds <- sample_test %>% filter(test_preds > threshold)

ggplot(positive_preds %>% 
         gather(starts_with("score"),key = "key",value = "score"),
       aes(x = interaction(key,outcome_any), y = score, dodge = outcome_any)) +
    coord_flip() + 
    geom_boxplot()
```


```{r}
# Requires sample_test with predictions

sample_test <- sample_test %>% 
  mutate(rank = rank(desc(prediction)))

# Ranks of defaults
defaults <- sample_test %>% filter(outcome == 'default')
View(defaults %>% select(siren, rank))
```

```{r}
top100 <- sample_test %>% filter(rank <= 100) %>% arrange(rank)

View(top100 %>% select(siren, siret, prediction, starts_with("score")))
```

```{r}
ggplot(sample_test, aes(x = rank, y = score_notapme)) +
         geom_smooth()

ggplot( sample_test   %>%
  gather(starts_with("score"), key = "key", value = "score"),
  aes(x = rank, y = score, group = key, color = key)
  ) +
  geom_smooth()
  

```

```{r}
# top100 compared to rest
top100 <- sample_test %>% mutate(ind_top100 = (rank <= 100))

ggplot(top100 %>%
  gather(starts_with("score"), key = "key", value = "score"), aes(x=interaction(key,ind_top100), y=score, dodge = key,color=ind_top100)) +
         geom_boxplot() +
  coord_flip()
```

