---
title: "Dette_effectif_only"
author: "Pierre Camilleri"
date: "6 avril 2018"
output: html_document
---


```{r}
# Collecting database
set.seed(1409)

database_signauxfaibles <- database_connect()
table_wholesample <-
    collect_wholesample(db = database_signauxfaibles, table = "wholesample")
```

```{r}
table_wholesample_prep <- objective_RJ_LJ_PS(table_wholesample)
table_wholesample_prep <- table_wholesample_prep %>%
  mutate(outcome = factor(outcome, levels = c(TRUE,FALSE), labels =  c("default", "non_default")))
```


```{r}
table_wholesample_sel <-
  table_wholesample_prep %>% 
  mutate(dette = (montant_part_patronale + montant_part_ouvriere)/effectif) %>% 
  select(
    siret,
    periode,
    outcome,
    outcome_any,
    date_defaillance,
    dette
  )
```

```{r}

ts_wholesample <-  table_wholesample_sel %>%
  group_by(siret) %>% 
    mutate(periode = as.Date(periode)) %>% 
  arrange(periode) %>% 
  filter(periode >= as.Date("2013-01-01"), periode <= as.Date("2016-12-01")) %>%
  tidyr::complete(siret,periode,fill = list(0)) %>%
  fill(dette,.direction = 'down') %>% 
  fill(dette,.direction = 'up')

ts_wholesample <- ts_wholesample %>%
  spread_relative_periods("dette",12) 
  
ts_wholesample <- ts_wholesample %>%
  filter(periode >= as.Date("2015-01-01"), periode <= as.Date("2016-12-01"))


```

```{r}
detect_na(ts_wholesample)
detect_infinite(ts_wholesample)
```

```{r}
#provisoire
full_wholesample <- ts_wholesample %>% filter(complete.cases(ts_wholesample %>% select(-date_defaillance)))
```

```{r}
samples <-
  split_snapshot_each_month(
    ts_wholesample,
    date_inf = as.Date("2015-01-01"),
    date_sup = as.Date("2016-12-01")
  )

sample_train <- samples$train
cv_folds <- samples$cv_fold
sample_test <- samples$test
```



```{r}
sample_train <-
  OSTSC(
    sample_train %>% select(starts_with('dette')) %>% as.matrix(),
    sample_train %>% select('outcome'),
    parallel = FALSE
    )
```

