<<<<<<< HEAD
---
title: "Evaluation"
author: "Pierre Camilleri"
date: "13 septembre 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
model = model

library(iml)
h2o.no_progress()
```

## R Courbe précision rappel et PR-AUC
```{r}
plot(1, type = 'n', xlab = "recall", ylab = "precision", xlim = c(0,1), ylim = c(0,1))

  perf <- h2o.performance(model, newdata = test.hex)
  pred <- h2o.predict(model, test.hex)
  true_res <- as.vector(as.numeric(test.hex['outcome']))

  precision <- h2o.precision(perf)
  recall <- h2o.recall(perf)
  lines(recall$tpr,precision$precision, col = rgb(runif(5),runif(5),runif(5)) )

  F2 <- h2o.F2(perf)
  precision_F2 <- precision$precision[which.max(F2$f2)]
  recall_F2 <- recall$tpr[which.max(F2$f2)]
  points(recall_F2, precision_F2, col = 'red', pch= 4)
  text(recall_F2, precision_F2,'F2', pos = 4, col = 'red')
  
  cat('F2 :', max(F2$f2), '\n')

  F1 <- h2o.F1(perf)
  precision_F1 <- precision$precision[which.max(F1$f1)]
  recall_F1 <- recall$tpr[which.max(F1$f1)]
  points(recall_F1, precision_F1, col = 'green', pch= 4)
  text(recall_F1, precision_F1,'F1', pos = 4, col = 'green')
  
    cat('F1 :', max(F1$f1), '\n')
    
    cat('AUC :', h2o.auc(perf), '\n')


  cat(str(pr.curve(scores.class0 = as.vector(pred$default), weights.class0 = true_res)))

```


## Table 
```{r}
h2o.confusionMatrix(perf,thresholds = F2$threshold[which.max(F2$f2)])
h2o.confusionMatrix(perf,thresholds = F1$threshold[which.max(F1$f1)])
```


### VALIDATION
```{r}

perf <- h2o.performance(model, valid = TRUE)
pred <- h2o.predict(model, validation.hex)
true_res <- as.vector(as.numeric(validation.hex['outcome']))

validation.df <- as.data.frame(validation.hex) # Il manque le SIRET
pred.df <- as.data.frame(pred$predict)
names(pred.df) <- "pred"
to_plot <- cbind(validation.df, pred.df)  %>% 
  group_by(siret) %>%
  arrange(periode) %>%
  filter(as.logical(default) || as.logical(failure)) %>%
  summarize(date_def = first(periode))

to_plot <- to_plot %>% 
  left_join(cbind(validation.df, pred.df)   %>% mutate(right_pred = pred == outcome), by = "siret") %>% 
  mutate(anticipation = elapsed_months(date_def,periode))

ggplot(to_plot, aes(x = anticipation, color = right_pred)) +
  geom_histogram(position = 'fill')
```

```{r}
to_plot <- cbind(test.df,pred.df) %>% 
  mutate(ok = pred == outcome)

ggplot(to_plot, aes(x = code_naf, color = ok)) +
  geom_bar(position = 'fill') + 
  geom_abline(slope = 0, intercept = mean(to_plot$ok))
```

# Partial dependence plot
```{r}

varimp <- h2o.varimp(model)
h2o.partialPlot(model, validation.hex, destination_key = "partial_dependence_plot_lgb_ref", cols = "resultat_net_consolide")
```
# IML

```{r}
features  <- as.data.frame(validation.hex[,x_medium])
response <- 2-as.numeric(as.factor(as.vector(validation.hex$outcome)))
pred <- function(model, newdata)  {
  results <- as.data.frame(h2o.predict(model, as.h2o(newdata)))
  return(results[[3L]])
}
```

```{r}
predictor.xgb <- Predictor$new(
  model = model,
  data = features,
  y = response,
  predict.fun = pred,
  class = "classification"
)
```

```{r}
tic()
imp.xgb <- FeatureImp$new(predictor.xgb, loss = "mse")
toc()
plot(imp.xgb) + ggtitle('XGB')

```

```{r}
tic()
part.xgb <- FeatureEffect$new(predictor.xgb, 'montant_part_patronale')
toc()
part.xgb_ice <- FeatureEffect$new(predictor.xgb, 'taux_marge_distrib_APE1', ice = TRUE)
part.xgb_ice$center(0)

plot(part.xgb) + ggtitle('xgb') + xlim(0,400000)
plot(part.xgb_ice) + ggtitle('xgb_ice')
```


```{r}
tic()
interact.xgb <- Interaction$new(predictor.xgb) 
toc()
plot(interact.xgb)
```
```{r}
tic()
shap.xgb <- Shapley$new(predictor.xgb, x.interest = features[903,])
toc()

shap_plot <- shap.xgb %>% plot()
thresh <- 10e-5 
to_remove <- abs(shap_plot$data[,"phi"]) < thresh
shap_plot$data <- shap_plot$data[!to_remove,]
shap_plot
```

