# Valeurs codées en dur, décommenter pour surcharger

# APP_BIND = ":3000"
# APP_DATA = "./data-raw/")
# DB_HOST = "127.0.0.1")
# DB_PORT = "27017")
# DB = "opensignauxfaibles"
# DB = "jason"
APP_DATA = "/home/christophe/Project/data-raw/"
